/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_shentanli_jnitest_JNITest */

#ifndef _Included_com_example_shentanli_jnitest_JNITest
#define _Included_com_example_shentanli_jnitest_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_shentanli_jnitest_JNITest
 * Method:    GetTest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_shentanli_jnitest_JNITest_GetTest
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
